version: '3'
services:
  app:
    build: .
    ports:
      - "5174:5173"    # Vite frontend (React)
      - "3001:3001"    # Node.js backend
    volumes:
      - .:/app         
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./server/.env  # Local Variables for development
